### PR TITLE
Test on 5.32

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by autarch** [comment]
I'm really close to getting this to run in Azure CI so I'm probably not going to merge this.

**Comment by oalders** [comment]
I'll close it then. Looks like there is other stuff going on here as well. There was something that came up in #metacpan about utf8 and 5.32, so I thought I'd test it out here, but it may actually just be #84.

**Comment by autarch** [comment]
You might have been bitten by a change in the latest Perl::Tidy. Check out the changes about `--character-encoding=guess` in https://metacpan.org/changes/distribution/Perl-Tidy

That seemed to be guessing wrong and converting UTF-8 in a comment to ISO-8859-1 when I ran tidyall against the Test-Class-Moose code. I had to explicitly set `--character-encoding=none` in my `perltidyrc` to work around it.

But it could also be a _combination_ of that new perltidy flag with tidyall's brokenness around UTF-8 in general.

I really need to get [precious](https://github.com/houseabsolute/precious/) a bit farther along. It doesn't have these sorts of encoding issues.

**Comment by oalders** [comment]
Thanks. That's helpful. I think we'd be happy to switch to `precious`. I just haven't tried it out yet.

**Pull request closed without merging**
