### PR TITLE
Consolidate git status code.

### PR DESCRIPTION
**Pull request by finn**
* Use Git::Util::git_uncommitted_files

### CODE REVIEW

**Comment by finn** [comment]
@autarch: This should fix issue #56

I didn't think it warranted any test changes since it was a refactor.

The relevant tests still pass for me locally which I am taking as a good sign. Waiting for the travis ci results.

**Comment by finn** [comment]
(I also corrected the version number listed in README.md)

**Comment by autarch** [comment]
There's no need to touch the README.md. It's auto-generated.

**Comment by autarch** [comment]
The rest of the PR looks good. Thanks! I'll merge once Travis passes.

**Comment by autarch** [comment]
Well, once it passes modulo a new test that's breaking for reasons outside of your control. Don't worry about the clean namespaces test.

**Comment by finn** [comment]
Great! Re-pushed w/o README changes.

**Comment by finn** [comment]
As predicted `t/author-clean-namespaces.t` failed -- but everything else looks ok in travis.

**Comment by autarch** [comment]
Thanks for working on this. I merged this from the CLI with a few small tweaks.

**Comment by finn** [comment]
:+1:

**Pull request closed without merging**
