### PR TITLE
Implement "Exclude filter" feature

### PR DESCRIPTION
**Pull request by shlomif**
To be able to skip unwanted plugins.

### CODE REVIEW

**Comment by autarch** [comment]
Hi Shlomi,

Thanks for your contribution!

However, tt's really hard to see what's going on in this PR for a couple reasons.

One, you've checked in changes to many generated files. While some of those changes would be things that would happen in release, some are changing things like the GitHub repo URI to point to your fork. In general, it's best to just not check these sorts of changes in for my projects, since they are automatically handled at release time.

Two, it seems like you've tidied the code either using an older version of `Perl::Tidy` or not using this project's tidyall config, so there are a bunch of formatting changes obscuring the actual functional changes in this PR.

If you could redo the PR without these that would be very helpful.

**Comment by shlomif** [comment]
> Hi Shlomi,
> 
> Thanks for your contribution!
> 
> However, tt's really hard to see what's going on in this PR for a couple reasons.
> 
> One, you've checked in changes to many generated files. While some of those changes would be things that would happen in release, some are changing things like the GitHub repo URI to point to your fork. In general, it's best to just not check these sorts of changes in for my projects, since they are automatically handled at release time.
> 
> Two, it seems like you've tidied the code either using an older version of `Perl::Tidy` or not using this project's tidyall config, so there are a bunch of formatting changes obscuring the actual functional changes in this PR.
> 
> If you could redo the PR without these that would be very helpful.

Hi Dave!

Thanks for the input.

I used "git co master --" and git rebase so hopefully it will be ok. BTW, I use PerlTidy 20191203 which is the most recent version. The dzil setup seems to be somewhat error-causing. ☹

**Comment by shlomif** [comment]
Hi @autarch ,

> I have a couple questions:
> 
>     1. Did you know about the "mode" feature? You can associate plugins with an arbitrary string using the "mode" config key. Then you can pass a `--mode` to `tidyall` and it will only pick plugins for that mode. While this doesn't allow excluding arbitrary plugins on each run, is it sufficient for what you want to do?
> 

No, I wish to exclude specific plugins out of all the plugins being run, because I may add some more plugins in the future, which should also be included.

>     2. Why implement this as an env var rather than a CLI option? That seems a bit arbitrary and confusing.

I used an env var because I sometimes do not call tidyall directly but rather from [gnumake](https://www.gnu.org/software/make/) or similar, and I also want the excluded filter to persist within the shell session. Is there a better way?

**Comment by shlomif** [comment]
@autarch : hi! Ping.

**Comment by autarch** [comment]
> Hi @autarch ,
> 
> > I have a couple questions:
> > ```
> > 1. Did you know about the "mode" feature? You can associate plugins with an arbitrary string using the "mode" config key. Then you can pass a `--mode` to `tidyall` and it will only pick plugins for that mode. While this doesn't allow excluding arbitrary plugins on each run, is it sufficient for what you want to do?
> > ```
> 
> No, I wish to exclude specific plugins out of all the plugins being run, because I may add some more plugins in the future, which should also be included.

But couldn't you do this with the `mode` config key? For example, if you have 10 plugins and 8 have a `mode = "foo"` defined, then when you run `tidyall --mode foo` you get just those 8. If you add a new plugin you can either add the `mode` key or not.

I think I need to better understand your exact use case.

> > ```
> > 2. Why implement this as an env var rather than a CLI option? That seems a bit arbitrary and confusing.
> > ```
> 
> I used an env var because I sometimes do not call tidyall directly but rather from [gnumake](https://www.gnu.org/software/make/) or similar, and I also want the excluded filter to persist within the shell session. Is there a better way?

My main issue is that this would be the _only_ setting that was set via an env var instead of a CLI argument. None of the current options can be set via an env var.

So I think any new argument would need to be supported via the CLI. It might make sense to have an env var for this option, as well as for others.

Though again, it really seems like the `mode` argument would do what you need. Adding a `TIDYALL_MODE` env var would make sense to me.

**Comment by shlomif** [comment]
Hi @autarch !

> > Hi @autarch ,
> > > I have a couple questions:
> > > ```
> > > 1. Did you know about the "mode" feature? You can associate plugins with an arbitrary string using the "mode" config key. Then you can pass a `--mode` to `tidyall` and it will only pick plugins for that mode. While this doesn't allow excluding arbitrary plugins on each run, is it sufficient for what you want to do?
> > > ```
> > 
> > 
> > No, I wish to exclude specific plugins out of all the plugins being run, because I may add some more plugins in the future, which should also be included.
> 
> But couldn't you do this with the `mode` config key? For example, if you have 10 plugins and 8 have a `mode = foo` defined, then when you run `tidyall --mode foo` you get just those 8. If you add a new plugin you can either add the `mode` key or not.
> 
> I think I need to better understand your exact use case.
> 

Based on https://metacpan.org/dist/Code-TidyAll/view/bin/tidyall#MODES it seems I can use `except_modes`. Thanks!

> > > ```
> > > 2. Why implement this as an env var rather than a CLI option? That seems a bit arbitrary and confusing.
> > > ```
> > 
> > 
> > I used an env var because I sometimes do not call tidyall directly but rather from [gnumake](https://www.gnu.org/software/make/) or similar, and I also want the excluded filter to persist within the shell session. Is there a better way?
> 
> My main issue is that this would be the _only_ setting that was set via an env var instead of a CLI argument. None of the current options can be set via an env var.
> 
> So I think any new argument would need to be supported via the CLI. It might make sense to have an env var for this option, as well as for others.
> 
> Though again, it really seems like the `mode` argument would do what you need. Adding a `TIDYALL_MODE` env var would make sense to me.

I see. We can opt to read CLI arguments from an env var too (using [GetOptionsFromString](https://metacpan.org/pod/Getopt::Long#Parsing-options-from-an-arbitrary-string) / etc.).

As far as I'm concerned, this PR can be closed,

**Pull request closed without merging**
