### PR TITLE
fix issue#43

### PR DESCRIPTION
**Pull request by shlomif**
See: https://github.com/houseabsolute/perl-code-tidyall/issues/43

Note that the dzil set-up of this repo is really time consuming and flakey

### CODE REVIEW

**Comment by autarch** [comment]
> Note that the dzil set-up of this repo is really time consuming and flakey

Could you be more specific?

**Comment by shlomif** [comment]
On Wed, 24 Nov 2021 07:34:53 -0800
Dave Rolsky ***@***.***> wrote:

> > Note that the dzil set-up of this repo is really time consuming and flakey  
> 
> Could you be more specific?
> 

Hi! i'll try to get to that later.

-- 

Shlomi Fish       https://www.shlomifish.org/
My Photos - https://www.flickr.com/photos/shlomif/

I understood what Monads are for 5 minutes. Then I had to let go of the
understanding. It was too intense to be kept inside my head.
    — An Israeli Open Source Software Enthusiast.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by autarch** [comment]
Merged, thanks!

**Comment by shlomif** [comment]
On Wed, 24 Nov 2021 13:20:14 -0800
Dave Rolsky ***@***.***> wrote:

> Merged, thanks!
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
First stop for Perl beginners - https://perl-begin.org/

The Knights Who Say “Ni” once said “Ni” to Chuck Norris. They are now no longer
The Knights Who Say “Ni”.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Pull request merged**
